### ISSUE TITLE
Unhandled Exception: Concurrent modification during iteration

### ISSUE THREAD

**Issue by harryhieunguyen** [Aikyuichi/notification_center.dart#3]
Error usually appear as 
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Concurrent modification during iteration: Instance(length:11) of '_GrowableList'.
#0      ListIterator.moveNext (dart:_internal/iterable.dart:348:7)
#1      NotificationCenter.unsubscribe (package:notification_center/notification_center.dart:44:30)
<asynchronous suspension> 
```

and I found in this part 

 /// Remove from the center the subscribers of [notificationId].
```
Future<void> unsubscribe(String notificationId) async {
    if (_notifications.containsKey(notificationId)) {
      final subscribers = _notifications[notificationId]!;
      for (var subscriber in subscribers) {
        subscriber.onCancel = null;
        await subscriber.cancel();
      }
      _notifications.remove(notificationId);
    }
  }
```
Currently I add [... subscribers] as duplicate list to avoid error, but it is just temporary
You may consider this after new update 
Thank you for your work

**Comment by Aikyuichi** [comment]
Hi
Fixed on 1.0.2
